name: Generate Datas

on:
<<<<<<< HEAD
  schedule: # execute every sunday
    - cron: "0 0 * * Sun"
=======
  schedule: # execute every 120 hours
    - cron: "* */120 * * *"
>>>>>>> ffe969e258737d0bbe75d20e61687b1de2d517dd
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Himal-Thapa1
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
